let baciasInfo = [];

baciasInfo = [

{ id: '0', nome: 'Acre', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/1H3Dg7jT4gInGMC'},
{ id: '1', nome: 'Afogados de Ingazeira', amb: 'Terrestre', link:''},
{ id: '2', nome: 'Alagoas_M', amb: 'Marítimo', link:''},
{ id: '3', nome: 'Alagoas_T', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/UIgVZobfQwyLeA1'},
{ id: '4', nome: 'Alto Tapajós', amb: 'Terrestre', link:''},
{ id: '5', nome: 'Amazonas', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/IPNA8z7hO1vHsxI'},
{ id: '6', nome: 'Araripe', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/ygv6FS5D91I6mef'},
{ id: '7', nome: 'Bananal', amb: 'Terrestre', link:''},
{ id: '8', nome: 'Barreirinhas_M', amb: 'Marítimo', link:''},
{ id: '9', nome: 'Barreirinhas_T', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/WXhrH3KTduh9IVM'},
{ id: '10', nome: 'Betânia', amb: 'Terrestre', link:''},
{ id: '11', nome: 'Bom Nome', amb: 'Terrestre', link:''},
{ id: '12', nome: 'Bragança-Vizeu', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/Ril60VKtkXRGyE0'},
{ id: '13', nome: 'Camamu-Almada_M', amb: 'Marítimo', link:''},
{ id: '14', nome: 'Camamu-Almada_T', amb: 'Terrestre', link:''},
{ id: '15', nome: 'Campos_M', amb: 'Marítimo', link:''},
{ id: '16', nome: 'Campos_T', amb: 'Terrestre', link:''},
{ id: '17', nome: 'Campos_T', amb: 'Terrestre', link:''},
{ id: '18', nome: 'Ceará_M', amb: 'Marítimo', link:''},
{ id: '19', nome: 'Ceará_T', amb: 'Terrestre', link:''},
{ id: '20', nome: 'Cedro', amb: 'Terrestre', link:''},
{ id: '21', nome: 'Cumuruxatiba_M', amb: 'Marítimo', link:''},
{ id: '22', nome: 'Cumuruxatiba_T', amb: 'Terrestre', link:''},
{ id: '23', nome: 'Curitiba', amb: 'Terrestre', link:''},
{ id: '24', nome: 'Espírito Santo_M', amb: 'Marítimo', link:''},
{ id: '25', nome: 'Espírito Santo_T', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/MSYSOk8HApYAT7w'},
{ id: '26', nome: 'Foz do Amazonas_M', amb: 'Marítimo', link:''},
{ id: '27', nome: 'Foz do Amazonas_T', amb: 'Terrestre', link:''},
{ id: '28', nome: 'Icó', amb: 'Terrestre', link:''},
{ id: '29', nome: 'Iguatu', amb: 'Terrestre', link:''},
{ id: '30', nome: 'Irecê', amb: 'Terrestre', link:''},
{ id: '31', nome: 'Itaboraí', amb: 'Terrestre', link:''},
{ id: '32', nome: 'Jacuípe', amb: 'Marítimo', link:''},
{ id: '33', nome: 'Jatobá', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/iUEhPczwLZyFhGy'},
{ id: '34', nome: 'Jequitinhonha_M', amb: 'Marítimo', link:''},
{ id: '35', nome: 'Jequitinhonha_T', amb: 'Terrestre', link:''},
{ id: '36', nome: 'Lençóis', amb: 'Terrestre', link:''},
{ id: '37', nome: 'Lima Campos', amb: 'Terrestre', link:''},
{ id: '38', nome: 'Madre de Díos', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/1H3Dg7jT4gInGMC'},
{ id: '39', nome: 'Malhada Vermelha', amb: 'Terrestre', link:''},
{ id: '40', nome: 'Marajó', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/vPEuDaXVoAqLZGx'},
{ id: '41', nome: 'Mirandiba', amb: 'Terrestre', link:''},
{ id: '42', nome: 'Mucuri_M', amb: 'Marítimo', link:''},
{ id: '43', nome: 'Mucuri_T', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/MSYSOk8HApYAT7w'},
{ id: '44', nome: 'Pajeú', amb: 'Terrestre', link:''},
{ id: '45', nome: 'Pantanal', amb: 'Terrestre', link:''},
{ id: '46', nome: 'Pará-Maranhão', amb: 'Marítimo', link:''},
{ id: '47', nome: 'Paraná', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/z0XoautAuswCSbf'},
{ id: '48', nome: 'Parecis', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/1OivrPY3VNVSoiv'},
{ id: '49', nome: 'Parnaíba', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/zTQ17CWbL2Wvx5f'},
{ id: '50', nome: 'Pelotas_M', amb: 'Marítimo', link:''},
{ id: '51', nome: 'Pelotas_T', amb: 'Terrestre', link:''},
{ id: '52', nome: 'Pernambuco-Paraiba_M', amb: 'Marítimo', link:''},
{ id: '53', nome: 'Pernambuco-Paraiba_T', amb: 'Terrestre', link:''},
{ id: '54', nome: 'Potiguar_M', amb: 'Marítimo', link:''},
{ id: '55', nome: 'Potiguar_T', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/mCuF7AzcaAztmoA'},
{ id: '56', nome: 'Recôncavo_M', amb: 'Marítimo', link:''},
{ id: '57', nome: 'Recôncavo_T', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/87Ny6plVJXljL0C'},
{ id: '58', nome: 'Resende', amb: 'Terrestre', link:''},
{ id: '59', nome: 'Rio do Peixe', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/8J7SFIsDwkxs0r8'},
{ id: '60', nome: 'Santos', amb: 'Marítimo', link:''},
{ id: '61', nome: 'São Francisco', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/raz73BsTFYy9emP'},
{ id: '62', nome: 'São José de Belmonte', amb: 'Terrestre', link:''},
{ id: '63', nome: 'São Luis', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/j2vquXFrz05VzUg'},
{ id: '64', nome: 'São Paulo', amb: 'Terrestre', link:''},
{ id: '65', nome: 'SEAL_M', amb: 'Marítimo', link:''},
{ id: '66', nome: 'Sergipe_T', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/3JDqGW6H8EtmXOJ'},
{ id: '67', nome: 'Socorro-Santo Ignácio', amb: 'Terrestre', link:''},
{ id: '68', nome: 'Solimões', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/DKD0oj9FsZAU8tI'},
{ id: '69', nome: 'Tacutu', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/Ii5FEOWeLJRw5Qp'},
{ id: '70', nome: 'Taubaté', amb: 'Terrestre', link:''},
{ id: '71', nome: 'Tucano Central', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/CsrfPDvjMGmxlEY'},
{ id: '72', nome: 'Tucano Norte', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/1p76hGJhZc2Szae'},
{ id: '73', nome: 'Tucano Sul', amb: 'Terrestre', link:'https://reate.cprm.gov.br/arquivos/index.php/s/RjB46l9VOkiKEd7'},
{ id: '74', nome: '', amb: ' ', link:''},
];

//export { baciasInfo };